export const gbpLocation = {
  storeName: "Main Kingston Cannabis",
  domain: "www.mainkingstoncannabis.ca",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "615 Kingston Rd, Toronto, ON M4E 1R3",
  streetAddress: "615 Kingston Rd",
  postalCode: "M4E 1R3",
  phone: "+1 289 460 0130",
  phoneIntl: "+12894600130",
  neighborhood: "Kingston Road / Upper Beaches",
  nearbyAreas: ["Kingston Road", "Main Street", "Upper Beaches", "East Toronto", "Danforth", "Victoria Park", "Birch Cliff", "Scarborough Southwest", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.6786661",
  longitude: "-79.298503",
  hours: ["Open 24 Hours"],
  seoTitle: "Main Kingston Cannabis | Weed Dispensary in Toronto",
  metaDescription: "Main Kingston Cannabis is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Kingston Road", "Main Street", "Upper Beaches"],
  introVariant: "Main Kingston Cannabis is a local weed dispensary in the Upper Beaches, located at 615 Kingston Rd where Kingston Road meets Main Street. Adults 19+ can browse menu categories including flower, pre-rolls, edibles, THC vapes, concentrates, shatter, CBD oils, and accessories before visiting.",
  neighborhoodDescription: "Located on the Kingston Road / Upper Beaches strip, the shop sits in the East End retail block around Main Street, with Woodbine Beach to the south and the Danforth to the north.",
  parkingNote: "Street parking lines Kingston Road around 615 Kingston Rd. Check posted signs on the block before you leave the car.",
  transitNote: "A short walk south of Main Street Station on Line 2. The 64 Main bus follows Main Street; the 503 Kingston Rd streetcar serves the corridor when in service.",
  sectionTitle: "Serving Customers Near Kingston Road and Main Street"
};
