// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "Main Kingston Cannabis",
  domain: "mainkingstoncannabis.ca",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "615 Kingston Rd, Toronto, ON M4E 1R3",
  streetAddress: "615 Kingston Rd",
  postalCode: "M4E 1R3",
  phone: "(905) 467-0615",
  phoneIntl: "+19054670615",
  neighborhood: "Main Street / Kingston Road / East Toronto",
  nearbyAreas: ["Main Street", "Kingston Road", "East Toronto", "Upper Beaches", "Danforth", "Victoria Park", "Birch Cliff", "Scarborough Southwest", "TTC"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "",
  latitude: "43.6766",
  longitude: "-79.2941",
  hours: ["Open 24 Hours"],
  seoTitle: "Main Kingston Cannabis | Weed Dispensary in Toronto",
  metaDescription: "Main Kingston Cannabis is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Main Street", "Kingston Road", "East Toronto"],
  introVariant: "Main Kingston Cannabis is a local weed dispensary in Toronto, located at 615 Kingston Rd. We serve adults 19+ looking for quality weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, shatter, CBD oils, and accessories. Whether you are searching for a weed dispensary near Main Street / Kingston Road / East Toronto, a cannabis store in Toronto, or a local weed shop close to Kingston Road, our friendly team is here to help you find the right product.",
  neighborhoodDescription: "Located in the vibrant Main Street / Kingston Road / East Toronto district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking is available along Kingston Road",
  transitNote: "A short walk from Main Street Station and accessible via local TTC streetcar routes.",
  sectionTitle: "Serving Customers Near Main Street and Kingston Road"
};
