import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
const config=read("next.config.ts"),products=read("app/lib/products.ts"),tiers=read("app/lib/tierSeoContent.ts"),sitemap=read("app/sitemap.ts"),nav=read("app/components/Navbar.tsx"),delivery=read("app/weed-delivery-toronto/page.tsx"),resources=read("app/resources/resourceData.ts");
const migrations=[["/exotic","/exotic-weed"],["/premium","/premium-weed"],["/aaa","/aaa-weed"],["/aa","/aa-weed"],["/budget","/budget-weed"],["/delivery","/weed-delivery-toronto"],["/resources","/weed-resources"],["/resources/menu-guide","/resources/cannabis-menu-guide"],["/resources/flower-guide","/resources/weed-flower-guide"],["/resources/value-guide","/resources/weed-value-guide"],["/resources/kingston-road-east-toronto-visit-guide","/resources/kingston-road-east-toronto-weed-visit-guide"]];
test("direct V2 redirects",()=>{for(const [a,b] of migrations){assert.ok(config.includes(`source: "${a}", destination: "${b}", permanent: true`));}});
test("Weed-first tier names and canonicals",()=>{for(const [n,s] of [["Weed Exotic","exotic-weed"],["Weed Premium","premium-weed"],["Weed AAA+","aaa-weed"],["Weed AA","aa-weed"],["Weed Budget","budget-weed"]]){assert.ok(products.includes(`name: "${n}"`));assert.ok(products.includes(`slug: "${s}"`));assert.ok(nav.includes(`href: "/${s}", label: "${n}"`));assert.ok(tiers.includes(`${n} & Cannabis Flower Toronto`));}});
test("delivery and resources use new owners",()=>{assert.match(delivery,/Weed Delivery Toronto \| Main Kingston cannabis/);assert.match(sitemap,/weed-delivery-toronto/);assert.doesNotMatch(sitemap,/`\$\{BASE\}\/delivery`/);for(const s of ["cannabis-menu-guide","weed-flower-guide","weed-value-guide","kingston-road-east-toronto-weed-visit-guide"])assert.ok(resources.includes(`slug: "${s}"`));});
